services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "star_track-backend"
    ports:
      - "8001:8000"
    restart: always
    command: "uvicorn main:app --host 0.0.0.0"
    env_file: .env_example
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: "star_track-db"
    ports:
      - "5432:5432"
    restart: always
    env_file: .env_example
    volumes:
      - .:/data/db/var/lib/postgresql/data
